### ISSUE TITLE
Possibility to set custom background?

### ISSUE THREAD

**Issue by lillelilje** [diegovazquez/ASCIILinuxVirtualWebCam#1]
This application is great - and making it just output the detected body without the background is easy enoug (Removing `frame = asciiart(frame, SC, GCF)` )

But - How would one add a custom background?

I realize that this might be out of scope, and also something that google should be able to tell me, I just haven't been able to successfully wrap my head around how to accomplish this.

**Comment by diegovazquez** [comment]
I will add this function soon.

**Comment by diegovazquez** [comment]
Done. The relevant code is:

        alpha = mask.astype(float) / 255
        foreground = cv2.multiply(alpha, frame, dtype=cv2.CV_32F)
        background = cv2.multiply(1.0 - alpha, backgroundImage, dtype=cv2.CV_32F)
        frame = cv2.add(foreground, background)
        frame = np.uint8(frame)

**Comment by lillelilje** [comment]
Brilliant! Thank you.
